"""Prep for AI configuration generator for Microsoft Fabric models.

Note: Open Question #4 resolved — no Fabric REST API exists for programmatic
application of Prep for AI configurations. This module produces a manual
application guide as a JSON configuration file.
"""

from dataclasses import dataclass
from typing import TYPE_CHECKING

from fabric_ai_meta.models.metadata import (
    MeasureCategory,
    ColumnRole,
    SemanticModelMeta,
    TableMeta,
    TableType,
)
from fabric_ai_meta.llm.prompts import AI_INSTRUCTIONS_PROMPT

if TYPE_CHECKING:
    from fabric_ai_meta.llm.client import FabricLLMClient
    from fabric_ai_meta.generator.description_backfill import DescriptionBackfill


@dataclass
class PrepForAIConfig:
    """Output that maps to Power BI's Prep for AI feature."""

    # AI Data Schema — which tables/columns to include
    included_tables: list[str]
    excluded_columns: dict[str, list[str]]  # table -> columns to exclude

    # AI Instructions — natural language guidance
    ai_instructions: str  # Generated prompt text for the model

    # Verified Answers — question-to-DAX mappings
    verified_answers: list[dict]  # [{"question": "...", "dax": "...", "description": "..."}]

    # Missing descriptions — generated by LLM
    generated_descriptions: dict[str, dict[str, str]]  # table -> object -> description


def generate_prep_for_ai(
    model: SemanticModelMeta,
    llm_client: "FabricLLMClient",
    backfill: "DescriptionBackfill | None" = None,
) -> PrepForAIConfig:
    """Generate a Prep for AI configuration from a semantic model.

    Produces a manual application guide (JSON) since no programmatic Fabric
    REST API exists for applying Prep for AI configurations.
    """
    included_tables = [
        t.name
        for t in model.tables
        if not t.is_hidden and t.table_type != TableType.STAGING
    ]

    excluded_columns = _build_excluded_columns(model)

    ai_instructions = _generate_ai_instructions(model, llm_client)

    verified_answers = _build_verified_answers(model)

    if backfill is not None:
        generated_descriptions = dict(backfill.column_descriptions)
    else:
        generated_descriptions = _generate_missing_descriptions(model, llm_client)

    return PrepForAIConfig(
        included_tables=included_tables,
        excluded_columns=excluded_columns,
        ai_instructions=ai_instructions,
        verified_answers=verified_answers,
        generated_descriptions=generated_descriptions,
    )


def _build_excluded_columns(model: SemanticModelMeta) -> dict[str, list[str]]:
    """Build the excluded columns map: hidden, sort-by, and keyless internal keys."""
    excluded: dict[str, list[str]] = {}
    for table in model.tables:
        to_exclude = []
        for col in table.columns:
            if col.is_hidden:
                to_exclude.append(col.name)
            elif col.role == ColumnRole.SORT:
                to_exclude.append(col.name)
            elif col.role in (ColumnRole.KEY, ColumnRole.FOREIGN_KEY) and not col.description:
                to_exclude.append(col.name)
        if to_exclude:
            excluded[table.name] = to_exclude
    return excluded


def _generate_ai_instructions(
    model: SemanticModelMeta,
    llm_client: "FabricLLMClient",
) -> str:
    """Call LLM with AI_INSTRUCTIONS_PROMPT and return the generated text."""
    visible_tables = [t for t in model.tables if not t.is_hidden]
    table_summary = ", ".join(
        f"{t.name} ({t.table_type.value})" for t in visible_tables
    )

    all_measures = [
        m for t in model.tables for m in t.measures if not m.is_hidden
    ]
    measure_summary = ", ".join(
        f"[{m.name}] ({m.category.value})" for m in all_measures[:10]
    )

    rel_lines = [
        f"{r.from_table}[{r.from_column}] → {r.to_table}[{r.to_column}]"
        for r in model.relationships
    ]
    relationship_summary = "; ".join(rel_lines) if rel_lines else "No relationships."

    prompt = AI_INSTRUCTIONS_PROMPT.format(
        model_name=model.name,
        table_summary=table_summary,
        measure_summary=measure_summary,
        relationship_summary=relationship_summary,
    )
    return llm_client.call(prompt, max_tokens=2000)


def _build_verified_answers(model: SemanticModelMeta) -> list[dict]:
    """Generate verified Q&A pairs for each time-intelligence measure."""
    answers = []
    for table in model.tables:
        for measure in table.measures:
            if measure.category == MeasureCategory.TIME_INTELLIGENCE and not measure.is_hidden:
                description = measure.description or measure.ai_description or ""
                answers.append({
                    "question": f"What is {measure.name} for the current period?",
                    "dax": measure.dax_expression,
                    "description": description,
                })
    return answers


def _generate_missing_descriptions(
    model: SemanticModelMeta,
    llm_client: "FabricLLMClient",
) -> dict[str, dict[str, str]]:
    """Call LLM to generate descriptions for tables and columns that lack them."""
    result: dict[str, dict[str, str]] = {}
    for table in model.tables:
        if table.is_hidden:
            continue
        table_descs: dict[str, str] = {}

        if not table.description:
            sibling_ctx = _sibling_table_descriptions(model, table.name)
            desc = llm_client.generate_description(
                "table",
                table.name,
                {"parent_table": table.name, "sibling_descriptions": sibling_ctx},
            )
            table_descs["__table__"] = desc

        for col in table.columns:
            if not col.description:
                sibling_ctx = _sibling_column_descriptions(table)
                desc = llm_client.generate_description(
                    "column",
                    col.name,
                    {
                        "parent_table": table.name,
                        "data_type": col.data_type,
                        "sibling_descriptions": sibling_ctx,
                    },
                )
                table_descs[col.name] = desc

        if table_descs:
            result[table.name] = table_descs

    return result


def _sibling_table_descriptions(model: SemanticModelMeta, exclude_table: str) -> str:
    lines = [
        f"{t.name}: {t.description}"
        for t in model.tables
        if t.name != exclude_table and t.description
    ]
    return "\n".join(lines[:5]) if lines else "None available."


def _sibling_column_descriptions(table: TableMeta) -> str:
    lines = [
        f"{col.name}: {col.description}"
        for col in table.columns
        if col.description
    ]
    return "\n".join(lines[:5]) if lines else "None available."
