table dim_customer
	lineageTag: cdb896da-4fb0-457f-a3be-640f12b0618d

	column id
		dataType: int64
		formatString: 0
		lineageTag: 347d0946-b8e7-4d7b-ad53-a916d3bfc45f
		summarizeBy: none
		sourceColumn: id

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column name
		dataType: string
		lineageTag: a4ccf485-30ae-4da9-b179-0b3949ac0a62
		summarizeBy: none
		sourceColumn: name

		annotation SummarizationSetBy = Automatic

	column email
		dataType: string
		lineageTag: 7bcd729e-5efb-42c7-827d-c1f5cf6e7bf2
		summarizeBy: none
		sourceColumn: email

		annotation SummarizationSetBy = Automatic

	column country
		dataType: string
		lineageTag: 05012602-2b06-49c4-a00f-d8fb3014c4e7
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column region
		dataType: string
		lineageTag: 3f0053ef-798f-4ca2-b9ad-3b3662dd544e
		summarizeBy: none
		sourceColumn: region

		annotation SummarizationSetBy = Automatic

	column loyalty_tier
		dataType: string
		lineageTag: 8a1cbcea-27b4-40ba-b4b8-7b467aaea286
		summarizeBy: none
		sourceColumn: loyalty_tier

		annotation SummarizationSetBy = Automatic

	column carbon_offset_opt_in
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 8feb8347-e21f-4865-a238-d68b13aaf523
		summarizeBy: none
		sourceColumn: carbon_offset_opt_in

		annotation SummarizationSetBy = Automatic

	partition dim_customer = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\claude-projects\datasets\out\footwear-sustainability-star\clean\dim_customer.csv"),[Delimiter=",", Columns=7, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"id", Int64.Type}, {"name", type text}, {"email", type text}, {"country", type text}, {"region", type text}, {"loyalty_tier", type text}, {"carbon_offset_opt_in", type logical}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

